### ISSUE TITLE
Dockerize the frontend application

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/katangapp-frontend#20]
We'd need the main command that will be executed on startup, like './my-project/start.sh' or similar.

**Comment by javierlopezdeancos** [comment]
Captain obvious

![image](http://vignette1.wikia.nocookie.net/uncyclopedia/images/1/15/CaptainobviousChooseOption.jpg)

**Comment by SyntaxChris** [comment]
Why would you guys dockerize a front end application to begin with?

**Comment by SyntaxChris** [comment]
Why would you guys dockerize a front end application to begin with?

**Comment by javierlopezdeancos** [comment]
Its only to more testable and more manageable for backend guys this side.

**Comment by mdelapenya** [comment]
Yes, it allows us to use the frontend without knowing anything about its build/run lifecycle. We just execute one docker command.

Besides, we are able deploy the application to a PaaS that manages container in a easy manner.
