### ISSUE TITLE
Redirect to root page when users comes with others urls

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/katangapp-frontend#36]

**Comment by mdelapenya** [comment]
Given: busco paradas y me devuelve resultado X
When: me muevo (cambian mis coordenadas) y hago swipe-down (misma página de resultados)
Then: se actualizan los resultados con la nueva ubicación (X')

Por tanto no debería volver al index, creo yo

**Comment by javierlopezdeancos** [comment]
Puedes poner esto como un bug o una feature? creo que esta fuera del scope de esta tarea 

Redirect to root page when users comes with others urls no significa que el usuario haga swipe-down, sigue dentro de la misma url

el problema a solucionar aqui es que cuando el usuario escribe katanga.io/#results va a la pagina de results, cuando debería ir al index hasta que implementemos otra feature
