### ISSUE TITLE
Create build for production

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/katangapp-frontend#41]
Update to webpack 2
Añadir varias mejoras en componentes y containers
Sistema de build a producción y desarrollo local

**Comment by victorg1991** [comment]
@javierlopezdeancos this web is hosted somewhere?

**Comment by mdelapenya** [comment]
We maybe deploy it on WeDeploy :)

**Comment by victorg1991** [comment]
Oh, cool! :)

**Comment by javierlopezdeancos** [comment]
I want to deploy in WeDeploy the  next week :) @victorg1991
