### ISSUE TITLE
Analize testing frameworks/tools to apply them to the project

### ISSUE THREAD

**Issue by felixortegam** [gdgtoledo/katangapp-frontend#52]

**Comment by felixortegam** [comment]
Qué os parece si usamos Jest como plataforma de testing?

Ha sido creada por la gente de Facebook, como React, y la docu tiene buena pinta (incluso en spanish).

http://facebook.github.io/jest/es-ES/

**Comment by javierlopezdeancos** [comment]
yo la estoy usando en una cosa y es putamente genial

- fácil de configurar
- rápida de ejecutar
- sensacional integración con react

elejida tool de testing

cierro esta issue pues
